### ISSUE TITLE
Local deployment gives "java.lang.NullPointerException: expected parameter 'user' to be non-null"

### ISSUE THREAD

**Issue by mklueh** [pulumi/pulumi-rke#129]
### What happened?

I'm trying to test this package with docker-desktop, however I fail to get it working, because it expects a user, but I'm not sure if I need one.

I can connect to the docker daemon using `docker -H tcp://localhost:2375 ps`, no user provided.

What am I missing?

### Expected Behavior

To connect to localhost

### Steps to reproduce

Try to deploy using this cluster args

```
        return ClusterNodeArgs
                .builder()
                .port("2375")
                .roles("worker")
                .sshAgentAuth(false)
            
//               .nodeName("host.docker.internal")

                //public ip of the host machine
                .address("127.0.0.1")

                .build();
    }
```

Tried several variants here

### Output of `pulumi about`

```
CLI          
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME  VERSION
java  unknown

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22000 Build 22000
Arch     x86_64

This project is written in java: executable='' version='openjdk 19 2022-09-20
OpenJDK Runtime Environment (build 19+36-2238)
OpenJDK 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)' java='' javac='19'

Current Stack: organization/infrastructure/dev

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:dev::infrastructure::pulumi:pulumi:Stack::infrastructure-dev
pulumi:providers:docker                            urn:pulumi:dev::infrastructure::pulumi:providers:docker::default_4_3_1
docker:index/remoteImage:RemoteImage               urn:pulumi:dev::infrastructure::docker:index/remoteImage:RemoteImage::ubuntuRemoteImage
com.myproject.infrastructure:core:cluster:Rancher  urn:pulumi:dev::infrastructure::com.myproject.infrastructure:core:cluster:Rancher::RancherDeployment
pulumi:providers:rke                               urn:pulumi:dev::infrastructure::pulumi:providers:rke::default_3_3_0
rke:index/cluster:Cluster                          urn:pulumi:dev::infrastructure::com.myproject.infrastructure:core:cluster:Rancher$rke:index/cluster:Cluster::rancher-cluster
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @mklueh. Thanks for reporting this issue. It looks like [`ClusterNodeArgs`](https://www.pulumi.com/registry/packages/rke/api-docs/cluster/#clusternode) has a required field: `user`. 

Can you try:
```patch
        return ClusterNodeArgs
                .builder()
                .port("2375")
                .roles("worker")
                .sshAgentAuth(false)
+               .user("<SSH User to Bastion Host>")
//               .nodeName("host.docker.internal")

                //public ip of the host machine
                .address("127.0.0.1")

                .build();
    }
```

**Comment by iwahbe** [comment]
I have opened https://github.com/pulumi/pulumi-java/issues/1199 to track the null pointer exception.

**Comment by mklueh** [comment]
Hey @iwahbe , thanks.

I've tried it with the user field and my windows user, as well as docker-user, but this did not work. What user would be the correct one?

**Comment by iwahbe** [comment]
> Hey @iwahbe , thanks.
> 
> I've tried it with the user field and my windows user, as well as docker-user, but this did not work. What user would be the correct one?

When you say it did not work, do you mean you didn't get the desired behavior or that you got a null pointer exception?

This should type check (without panics):
```yaml
type: rke:Cluster
properties:
   nodes:
    - port: "2375"
      roles:
        - "worker"
      sshAgentAuth: false
      address: "127.0.0.1"
      user: "<SSH User to Bastion Host>"
```

If that still throws, can you please post the stack trace for the exception?

**Comment by mikhailshilkov** [comment]
@mklueh Were you able to try the above?

**Comment by mklueh** [comment]
Hi @mikhailshilkov 

I haven't worked on it since then. Will check probably next week if I have time for it and give you more details
