### ISSUE TITLE
master is broken on generate_coverage_data

### ISSUE THREAD

**Issue by jazzyfresh** [pulumi/pulumi-rke#54]
### What happened?

It appears to have been broken for some time. All other tests on master pass.

https://github.com/pulumi/pulumi-rke/actions/runs/4481974623/jobs/7879602268#step:11:286
```
/home/runner/work/pulumi-rke/pulumi-rke/bin/pulumi-tfgen-rke` schema --out provider/cmd/pulumi-resource-rke
2023/03/21 17:39:04 [DEBUG] Using modified User-Agent: Terraform/0.12.7 pulumi
warning: Found <elided> in description for [rke_cluster]. The description and any examples will be dropped in the Pulumi provider.
warning: Resource rke_cluster contains an <elided> doc reference that needs updated
warning: 1 entity descriptions contained an <elided> reference and were dropped, including examples.
error: json: unsupported value: NaN
make: *** [Makefile:135: tfgen] Error 255
Error: Process completed with exit code 2.
```

### Expected Behavior

All tests on master should pass

### Steps to reproduce

https://github.com/pulumi/pulumi-rke/actions/runs/4481974623/jobs/7879602268#step:11:286

The `generate_coverage_data` step from the master.yml workflow fails on `make tfgen` with 
> error: json: unsupported value: NaN

I am unable to reproduce this error locally, `make tfgen` runs fine. I have only seen this error in CI in this step.

### Output of `pulumi about`

<img width="1706" alt="Screen Shot 2023-03-21 at 10 34 02 AM" src="https://user-images.githubusercontent.com/1182129/226788279-089f4307-760a-4461-814e-74a15f72a65a.png">

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jazzyfresh** [comment]
Found this while investigating auth for https://github.com/pulumi/pulumi-rke/issues/53

**Comment by jazzyfresh** [comment]
Related tickets
* https://github.com/golang/go/issues/25721
* https://github.com/golang/go/issues/3480

These issues were closed with status "Unfortunate". It seems that NaN is not supported by the official json encoder for Go...

**Comment by jazzyfresh** [comment]
A workaround by the folks at Grafana: https://github.com/grafana/metrictank/commit/5de7d6e3751901a23501e5fcd95f0b2d0604e8f4f
* before marshalling json
* double check if it's `NaN`
* replace it with `null` then proceed
```
func (p *Point) MarshalJSON() ([]byte, error) {
	if math.IsNaN(p.Val) {
		return []byte(fmt.Sprintf("[null, %d]", p.Ts)), nil
	}
	return []byte(fmt.Sprintf("[%f, %d]", p.Val, p.Ts)), nil
}
```

I don't know anything about how pulumi is marshalling json, but saving this as a note. Although I assume we'd want to avoid having NaNs around in the first place.

**Comment by lukehoban** [comment]
This does not seem to currently be a problem on master.  Closing out.

**Comment by lukehoban** [comment]
Reopening as this does appear to still be failing, though it is not causing the overall master job to fail.
