### ISSUE TITLE
Upgrade to latest RKE terraform provider?

### ISSUE THREAD

**Issue by rgl** [pulumi/pulumi-rke#8]
Can this be upgraded to latest RKE terraform provider? At the time of writing this was https://github.com/rancher/terraform-provider-rke/releases/tag/v1.2.4.

Can the version of RKE terraform provider that this repository is tracking be more explicitly mentioned in the README?

**Comment by stack72** [comment]
Ho @rgl 

Sorry I missed this update - I have sent a PR as such now - the last updates are always listed in our CHANGELOGs and called out as a specific step

Paul
